import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar, { type CurrentUser } from "@/app/components/Navbar";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  let currentUser: CurrentUser | null = null

  if (session?.user?.id) {
    const dbUser = await prisma.user.findUnique({
      where: { id: session.user.id },
      select: { avatarUrl: true },
    })
    currentUser = {
      id:        session.user.id,
      name:      session.user.name ?? '',
      email:     session.user.email ?? '',
      role:      session.user.role as CurrentUser['role'],
      avatarUrl: dbUser?.avatarUrl ?? null,
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
